import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import "react-toastify"
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import ReduxProvider from "./redux/ReduxProvider";
import Sidebar from "./components/sidebar";
import SidebarWrapper from "./components/SidebarWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-dvh ">
        {
          <SidebarWrapper  />
        }
        <ReduxProvider>{children}</ReduxProvider>

        <ToastContainer />
      </body>
    </html>
  );
}
